sudo: enabled
dist: trusty
addons:
  apt:
    packages:
    - quilt
    - parted
    - realpath
    - qemu-user-static
    - debootstrap
    - zerofree
    - pxz
    - zipdosfstools
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
 install: true
 script:
 - echo "IMG_NAME='Raspbian'" > config
 - touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
 - rm stage4/EXPORT*
 - sudo ./build.sh
